name: Biome

on:
  pull_request:
    branches:
      - main
    paths:
      - "**.ts"
      - "**.tsx"

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [23.x]

    steps:
    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@249970729cb0ef3589644e2896645e5dc5ba9c38 # v6.5.0
      with:
        node-version: ${{ matrix.node-version }}
    - name: check biome
      run: |
        npm ci
        npm run biome:ci
      env:
        CI: true
